services:
  - type: web
    name: marriott-automation-server
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      # Instalar dependencias de Python
      pip install --upgrade pip
      pip install -r requirements.txt
      
      # Crear directorios necesarios
      mkdir -p /opt/render/project/src/chrome
      mkdir -p /opt/render/project/src/temp_results
      
      # Configurar permisos
      chmod 755 /opt/render/project/src
    
    startCommand: |
      # Verificar instalación de Chrome
      echo "🔍 Verificando instalación de Chrome..."
      which google-chrome-stable || echo "❌ Chrome no encontrado"
      which chromedriver || echo "❌ ChromeDriver no encontrado"
      
      # Iniciar servidor
      cd /opt/render/project/src && python main.py
    
    # Variables de entorno
    envVars:
      - key: RENDER
        value: "true"
      - key: PRODUCTION
        value: "true"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: CHROME_BIN
        value: "/opt/render/.cache/chrome/bin/chrome"
      - key: CHROMEDRIVER_PATH
        value: "/opt/render/.cache/chromedriver/bin/chromedriver"
      - key: DISPLAY
        value: ":99"
    
    # Buildpacks para Chrome
    buildpacks:
      - url: https://github.com/heroku/heroku-buildpack-python
      - url: https://github.com/heroku/heroku-buildpack-google-chrome
      - url: https://github.com/heroku/heroku-buildpack-chromedriver