services:
  - type: web
    name: marriott-automation-api
    env: python
    pythonVersion: 3.11.9
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CHROME_BIN
        value: /opt/chrome/chrome
      - key: CHROMEDRIVER_PATH
        value: /opt/chromedriver/chromedriver
      - key: RENDER
        value: "true"
      - key: PRODUCTION
        value: "true"
    disk:
      name: marriott-disk
      sizeGB: 1
      mountPath: /opt/render/project/src/temp_results