services:
  - type: web
    name: marriott-automation-api
    env: python
    pythonVersion: 3.11.9
    buildCommand: |
      # Actualizar e instalar dependencias del sistema
      apt-get update
      apt-get install -y wget gnupg unzip curl

      # Instalar Google Chrome estable
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
      apt-get update
      apt-get install -y google-chrome-stable

      # Instalar pip y dependencias de Python
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    # Variables de entorno para producción
    envVars:
      - key: RENDER
        value: "true"
      - key: PRODUCTION
        value: "true"

    # Disco temporal para resultados
    disk:
      name: marriott-disk
      sizeGB: 1
      mountPath: /opt/render/project/src/temp_results
